# Generated by Django 4.2.16 on 2024-11-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('cnic_no', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('specialty', models.CharField(choices=[('GP', 'General Practitioner'), ('Pediatrician', 'Pediatrician'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Surgeon', 'Surgeon')], max_length=50)),
                ('date_hired', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
